name: Commitlint
on:
  pull_request:
    branches: [main, staging, dev]
  push:
    branches: [main, staging, dev]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx commitlint --from=origin/${{ github.base_ref || 'HEAD~10' }} --to=HEAD --verbose
