# .github/workflows/release-please.yml
name: Create Release PR

on:
  workflow_dispatch: {} # manual trigger; pick branch in the UI
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          config-file: release-please-config.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
