# .github/workflows/release-please.yml
name: Create Release PR

on:
  workflow_dispatch: {} # manual trigger; pick branch in the UI

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          # The branch you chose in the dispatch UI (e.g., main, staging, dev)
          target-branch: ${{ github.ref_name }}
          # Use manifest-based (advanced) config below
          config-file: release-please-config.json

      - name: Show outputs (optional)
        if: ${{ steps.rp.outputs.prs_created == 'true' }}
        run: |
          echo "Release PR(s) created."
          echo '${{ steps.rp.outputs.prs }}'
